/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author USUARIO
 */
public class vista_diagnostico extends javax.swing.JFrame {

    /**
     * Creates new form vista_llamada
     */
    public vista_diagnostico() {
        initComponents();
        //CSS
        this.setLocation(1100, 300);
        this.setTitle("Centro de llamadas COVID-19");
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cajaSintoma = new javax.swing.JTextField();
        letreroSecundario = new javax.swing.JLabel();
        letreroPrincipal = new javax.swing.JLabel();
        cajaDetalle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        botonRegistrar = new javax.swing.JButton();
        anuncio1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        cajaEnfermedad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cajaSintoma.setBackground(new java.awt.Color(3, 111, 158));
        cajaSintoma.setForeground(new java.awt.Color(255, 255, 255));
        cajaSintoma.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaSintoma.setBorder(null);
        cajaSintoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaSintomaActionPerformed(evt);
            }
        });
        jPanel1.add(cajaSintoma, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 140, -1));

        letreroSecundario.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        letreroSecundario.setForeground(new java.awt.Color(255, 255, 255));
        letreroSecundario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letreroSecundario.setText("Síntoma:");
        letreroSecundario.setFocusable(false);
        jPanel1.add(letreroSecundario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 70, 10));

        letreroPrincipal.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        letreroPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        letreroPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letreroPrincipal.setText("REGISTRO DE DIAGNOSTICOS");
        letreroPrincipal.setFocusable(false);
        jPanel1.add(letreroPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 10, 320, -1));

        cajaDetalle.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 10)); // NOI18N
        cajaDetalle.setForeground(new java.awt.Color(255, 255, 255));
        cajaDetalle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cajaDetalle.setText("  ");
        cajaDetalle.setFocusable(false);
        jPanel1.add(cajaDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 280, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 320, 20));

        botonRegistrar.setBackground(new java.awt.Color(255, 255, 255));
        botonRegistrar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        botonRegistrar.setForeground(new java.awt.Color(3, 111, 158));
        botonRegistrar.setText("REGISTRAR");
        botonRegistrar.setBorder(null);
        botonRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegistrarMouseClicked(evt);
            }
        });
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(botonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 80, 20));
        botonRegistrar.getAccessibleContext().setAccessibleName("");

        anuncio1.setBackground(new java.awt.Color(3, 111, 158));
        anuncio1.setFont(new java.awt.Font("Serif", 2, 14)); // NOI18N
        anuncio1.setForeground(new java.awt.Color(255, 255, 255));
        anuncio1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        anuncio1.setFocusable(false);
        jPanel1.add(anuncio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 320, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 120, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 120, 10));

        cajaEnfermedad.setBackground(new java.awt.Color(3, 111, 158));
        cajaEnfermedad.setForeground(new java.awt.Color(255, 255, 255));
        cajaEnfermedad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaEnfermedad.setBorder(null);
        cajaEnfermedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaEnfermedadActionPerformed(evt);
            }
        });
        jPanel1.add(cajaEnfermedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 140, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Enfermedad:");
        jLabel3.setFocusable(false);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 70, 10));

        fondo.setBackground(new java.awt.Color(102, 51, 0));
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo azul.png"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed

    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void botonRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegistrarMouseClicked

    private void cajaSintomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaSintomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaSintomaActionPerformed

    private void cajaEnfermedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaEnfermedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaEnfermedadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista_diagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista_diagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista_diagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista_diagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista_diagnostico().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel anuncio1;
    public static javax.swing.JButton botonRegistrar;
    public static javax.swing.JLabel cajaDetalle;
    public static javax.swing.JTextField cajaEnfermedad;
    public static javax.swing.JTextField cajaSintoma;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    public static javax.swing.JLabel letreroPrincipal;
    public static javax.swing.JLabel letreroSecundario;
    // End of variables declaration//GEN-END:variables

}
