/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author USUARIO
 */
public class vista_gestion extends javax.swing.JFrame {

    /**
     * Creates new form vista_opciones
     */
    public vista_gestion() {
        initComponents();
        cajaCedulaPaciente.setVisible(false);
        anuncioCedulaPaciente.setVisible(false);
        btnEliminarPaciente.setVisible(false);
        separador1.setVisible(false);
        separador2.setVisible(false);
        separador3.setVisible(false);
                
        cajaCedulaCita.setVisible(false);
        cajaFechaCita.setVisible(false);
        anuncioCedulaCita.setVisible(false);
        anuncioFecha.setVisible(false);
        btnActualizarFecha.setVisible(false);
        btnEliminarCita.setVisible(false);
//        this.setLocationRelativeTo(null);
        
        //CSS
        this.setLocation(700, 100);
        this.setTitle("Centro de llamadas COVID-19");
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SP = new javax.swing.JScrollPane();
        cajaLista = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        anuncioCedulaPaciente = new javax.swing.JLabel();
        cajaCedulaPaciente = new javax.swing.JTextField();
        btnEliminarPaciente = new javax.swing.JToggleButton();
        separador3 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        cajaCedulaCita = new javax.swing.JTextField();
        btnEliminarCita = new javax.swing.JToggleButton();
        anuncioFecha = new javax.swing.JLabel();
        cajaFechaCita = new javax.swing.JTextField();
        btnActualizarFecha = new javax.swing.JToggleButton();
        anuncioCedulaCita = new javax.swing.JLabel();
        separador2 = new javax.swing.JSeparator();
        separador1 = new javax.swing.JSeparator();
        anuncio1 = new javax.swing.JLabel();
        botonPacientes = new javax.swing.JToggleButton();
        botonCitas = new javax.swing.JToggleButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(3, 111, 158));

        jPanel1.setBackground(new java.awt.Color(3, 111, 158));
        jPanel1.setMinimumSize(new java.awt.Dimension(590, 264));
        jPanel1.setPreferredSize(new java.awt.Dimension(590, 264));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cajaLista.setEditable(false);
        cajaLista.setBackground(new java.awt.Color(207, 216, 223));
        cajaLista.setColumns(20);
        cajaLista.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        cajaLista.setForeground(new java.awt.Color(4, 78, 105));
        cajaLista.setRows(5);
        cajaLista.setBorder(null);
        cajaLista.setFocusable(false);
        SP.setViewportView(cajaLista);

        jPanel1.add(SP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 244));

        jPanel4.setBackground(new java.awt.Color(3, 111, 158));

        anuncioCedulaPaciente.setBackground(new java.awt.Color(3, 111, 158));
        anuncioCedulaPaciente.setForeground(new java.awt.Color(255, 255, 255));
        anuncioCedulaPaciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        anuncioCedulaPaciente.setText("Cédula");

        cajaCedulaPaciente.setBackground(new java.awt.Color(3, 111, 158));
        cajaCedulaPaciente.setForeground(new java.awt.Color(255, 255, 255));
        cajaCedulaPaciente.setBorder(null);
        cajaCedulaPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaCedulaPacienteActionPerformed(evt);
            }
        });

        btnEliminarPaciente.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminarPaciente.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnEliminarPaciente.setForeground(new java.awt.Color(3, 111, 158));
        btnEliminarPaciente.setText("Eliminar Paciente");
        btnEliminarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cajaCedulaPaciente)
                    .addComponent(btnEliminarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(anuncioCedulaPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(separador3, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(anuncioCedulaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(cajaCedulaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarPaciente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(separador3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(44, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));

        jPanel3.setBackground(new java.awt.Color(3, 111, 158));

        cajaCedulaCita.setBackground(new java.awt.Color(3, 111, 158));
        cajaCedulaCita.setForeground(new java.awt.Color(255, 255, 255));
        cajaCedulaCita.setBorder(null);

        btnEliminarCita.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminarCita.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnEliminarCita.setForeground(new java.awt.Color(3, 111, 158));
        btnEliminarCita.setText("Eliminar Cita");
        btnEliminarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCitaActionPerformed(evt);
            }
        });

        anuncioFecha.setBackground(new java.awt.Color(3, 111, 158));
        anuncioFecha.setForeground(new java.awt.Color(255, 255, 255));
        anuncioFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        anuncioFecha.setText("Fecha");

        cajaFechaCita.setBackground(new java.awt.Color(3, 111, 158));
        cajaFechaCita.setForeground(new java.awt.Color(255, 255, 255));
        cajaFechaCita.setBorder(null);

        btnActualizarFecha.setBackground(new java.awt.Color(255, 255, 255));
        btnActualizarFecha.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnActualizarFecha.setForeground(new java.awt.Color(3, 111, 158));
        btnActualizarFecha.setText("Actualizar");
        btnActualizarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarFechaActionPerformed(evt);
            }
        });

        anuncioCedulaCita.setBackground(new java.awt.Color(3, 111, 158));
        anuncioCedulaCita.setForeground(new java.awt.Color(255, 255, 255));
        anuncioCedulaCita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        anuncioCedulaCita.setText("Cédula");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(separador2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(anuncioCedulaCita, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cajaCedulaCita, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEliminarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(anuncioFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaFechaCita, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anuncioFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anuncioCedulaCita, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajaFechaCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaCedulaCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separador2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizarFecha)
                    .addComponent(btnEliminarCita))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 340, 100));

        anuncio1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        anuncio1.setForeground(new java.awt.Color(255, 255, 255));
        anuncio1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        anuncio1.setText("Generar informe");
        jPanel1.add(anuncio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 340, 19));

        botonPacientes.setBackground(new java.awt.Color(255, 255, 255));
        botonPacientes.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        botonPacientes.setForeground(new java.awt.Color(3, 111, 158));
        botonPacientes.setText("Pacientes");
        botonPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPacientesActionPerformed(evt);
            }
        });
        jPanel1.add(botonPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 106, -1));

        botonCitas.setBackground(new java.awt.Color(255, 255, 255));
        botonCitas.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        botonCitas.setForeground(new java.awt.Color(3, 111, 158));
        botonCitas.setText("Citas");
        botonCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCitasActionPerformed(evt);
            }
        });
        jPanel1.add(botonCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 106, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 330, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 330, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarPacienteActionPerformed

    private void btnEliminarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarCitaActionPerformed

    private void btnActualizarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarFechaActionPerformed

    private void botonCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCitasActionPerformed

    private void botonPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPacientesActionPerformed

    }//GEN-LAST:event_botonPacientesActionPerformed

    private void cajaCedulaPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaCedulaPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaCedulaPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista_gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista_gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista_gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista_gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista_gestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JScrollPane SP;
    public static javax.swing.JLabel anuncio1;
    public static javax.swing.JLabel anuncioCedulaCita;
    public static javax.swing.JLabel anuncioCedulaPaciente;
    public static javax.swing.JLabel anuncioFecha;
    public static javax.swing.JToggleButton botonCitas;
    public static javax.swing.JToggleButton botonPacientes;
    public static javax.swing.JToggleButton btnActualizarFecha;
    public static javax.swing.JToggleButton btnEliminarCita;
    public static javax.swing.JToggleButton btnEliminarPaciente;
    public static javax.swing.JTextField cajaCedulaCita;
    public static javax.swing.JTextField cajaCedulaPaciente;
    public static javax.swing.JTextField cajaFechaCita;
    public static javax.swing.JTextArea cajaLista;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JSeparator separador1;
    public javax.swing.JSeparator separador2;
    public javax.swing.JSeparator separador3;
    // End of variables declaration//GEN-END:variables
}
